//! Typed recorders/loggers from Boson Spectra schemas.
//!
//! Each type below is generated by a `spectra_schema!` / `spectra_metric!` invocation in
//! `schemas/`; the `*Logger` / `*Recorder` types are what [`crate::SpectraOpsLog`] (via
//! `ops_log`) and [`crate::sink_forward`] call to emit a row or bump a counter/gauge.
//!
//! # Examples
//!
//! ```rust,no_run
//! use boson_spectra_telemetry::helpers::BosonTasksEnqueuedRecorder;
//!
//! BosonTasksEnqueuedRecorder::record(
//!     1,
//!     serde_json::json!({"task_name": "send_email", "mode": "local"}),
//! );
//! ```

/// Row type and logger for the `boson_handler_error` event table.
pub use crate::schemas::boson_handler_error::{BosonHandlerError, BosonHandlerErrorLogger};
/// Recorder for the `boson_remote_errors` counter.
pub use crate::schemas::boson_remote_errors::BosonRemoteErrorsRecorder;
/// Row type and logger for the `boson_runtime_log` event table.
pub use crate::schemas::boson_runtime_log::{BosonRuntimeLog, BosonRuntimeLogLogger};
/// Recorder for the `boson_task_duration_ms` gauge.
pub use crate::schemas::boson_task_duration_ms::BosonTaskDurationMsRecorder;
/// Row type and logger for the `boson_task_log` event table.
pub use crate::schemas::boson_task_log::{BosonTaskLog, BosonTaskLogLogger};
/// Recorder for the `boson_tasks_completed` counter.
pub use crate::schemas::boson_tasks_completed::BosonTasksCompletedRecorder;
/// Recorder for the `boson_tasks_enqueued` counter.
pub use crate::schemas::boson_tasks_enqueued::BosonTasksEnqueuedRecorder;
/// Recorder for the `boson_tasks_failed` counter.
pub use crate::schemas::boson_tasks_failed::BosonTasksFailedRecorder;
